on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - name: Start selenoid
      uses: ajinx/selenoid@v1
    - uses: actions/checkout@v2
    - run: npm ci  
    - name: Run tests
      run: npm test
